### ISSUE TITLE
 package ‘SDMTools’ is not available (for R version 4.0.2)

### ISSUE THREAD

**Issue by NathanSkene** [fungenomics/cytobox#8]
Dependency on SDMTools should probably be dropped as that package is no longer maintained

**Comment by sjessa** [comment]
Hi Nathan, thanks for pointing this out! SDMTools isn't an explicit dependency of cytobox so we'll have to track down where it's required - I think it may be Seurat V2. We are currently working on a new iteration of cytobox, overhauled to work with Seurat V3/V4, so will likely leave this one as is to preserve compatibility with older versions of Seurat.
